language: java
jdk: oraclejdk7
deploy:
  provider: heroku
  api_key:
    secure: Zd1tn08hEJadSVIdMqmNj90uUdrOLWVOnZyCcjoDNWkt5dA3S8eNpLv+PerrFVUeevSeQzYntgNUbvJo6vMJmoC2rXgkWgaIAbnSd1udIVmX9dsC36vmuEVxKDpcxbEuoxSuR4mlFgxNB5v6m/WChKahgnNXCqMbDkcvwUaIgw8=
  app: ajtictac
  on:
    repo: AustanJotnar/tripping-spice
  after_script: 
  - "export DISPLAY=:99.0"
  - "export STAGING_SERVER=http://ajtictac.herokuapp.com/"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - rackup
  - sleep 3
  - "mvn test-compile failsafe:integration-test"
  - "sh -e /etc/init.d/xvfb stop"
  - "sh bin/selenium_test_xvfb"


