language: java
jdk: oraclejdk7
install:
  - mvn install -Dskip.integration.tests=true -Dskip.unit.tests=true -Dskip.pre.unit.test=true -Dskip.post.unit.test=true
  skip.integration.tests
deploy:
  provider: heroku
  api_key: 
    secure: Zd1tn08hEJadSVIdMqmNj90uUdrOLWVOnZyCcjoDNWkt5dA3S8eNpLv+PerrFVUeevSeQzYntgNUbvJo6vMJmoC2rXgkWgaIAbnSd1udIVmX9dsC36vmuEVxKDpcxbEuoxSuR4mlFgxNB5v6m/WChKahgnNXCqMbDkcvwUaIgw8=
  app: ajtictac-staging
  on:
    repo: AustanJotnar/tripping-spice
#install:
#  - mvn install -Dmaven.test.skip.integration.tests
before_install:
 -Dskip.integration.tests=true -skip.integration.tests=true
 # - "sh bin/success"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
#
after_deploy:
 - "sh bin/seleniumtravis"
after_script:
  - "sh -e /etc/init.d/xvfb stop"
after_failure:
  - "sh -e /bin/failure"