language: java
jdk: oraclejdk7
env:
  global:
    secure: QgyZde9u8WP2jX3QcndeUeAOE2YMVubRuj295aK26PkPIyZU//E1bWEhyTUlltCOeRTaZBA7m5S/bfVLkWZyN9R6ghFoLcdGDhu9zyrYOU8fl9/s9RMkWTJYmud/FY+EYU9ot9XtO+k+In5xA8ae/zJZjw4m2eS4fdVtpYQwgRI=
deploy:
  provider: heroku
  api_key:
    secure: Zd1tn08hEJadSVIdMqmNj90uUdrOLWVOnZyCcjoDNWkt5dA3S8eNpLv+PerrFVUeevSeQzYntgNUbvJo6vMJmoC2rXgkWgaIAbnSd1udIVmX9dsC36vmuEVxKDpcxbEuoxSuR4mlFgxNB5v6m/WChKahgnNXCqMbDkcvwUaIgw8=
  app: ajtictac
  on:
    repo: AustanJotnar/tripping-spice
  #Use this to install any prerequisites 
  #or dependencies necessary to run your build
before_script:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
   #- "sh -e deployherokustaging"
after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:ajtictac-staging.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - yes | heroku keys:add
  - yes | git push heroku 
  #
  - "sh -e bin/seleniumtravis"
  - "sh -e bin/success"
after_script:
 - "sh -e /etc/init.d/xvfb stop"
after_failure:
 - "sh -e /bin/failure"