language: java
jdk: oraclejdk7
deploy:
  provider: heroku
  api_key:
    secure: Zd1tn08hEJadSVIdMqmNj90uUdrOLWVOnZyCcjoDNWkt5dA3S8eNpLv+PerrFVUeevSeQzYntgNUbvJo6vMJmoC2rXgkWgaIAbnSd1udIVmX9dsC36vmuEVxKDpcxbEuoxSuR4mlFgxNB5v6m/WChKahgnNXCqMbDkcvwUaIgw8=
  app: ajtictac
  on:
    repo: AustanJotnar/tripping-spice
  after_script: 
    - "export STAGING_SERVER=http://ajtictac.herokuapp.com/"
    - " sh bin/selenium_test_xvfb"
